import { useLocalSearchParams } from 'expo-router';
import { ScrollView, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { ScreenHeader } from '@/components/ms/screen-header';
import { Body, BodyBold, Heading } from '@/components/ms/text';
import { MS } from '@/constants/mindshed';
import { LEGAL_DOCUMENTS_APPROVED } from '@/lib/legal-readiness';

const COPY = {
  privacy: { eyebrow: 'Pilot privacy notice', title: 'How this build handles data', intro: 'This screen describes the implemented pilot build. The final controller notice must be approved before production consent opens.', sections: [['Private on this device', 'Your display name, journal, check-in notes, support plan and daily plan are stored in the app’s encrypted native database. They are included only when you explicitly create an export.'], ['Optional pilot record', 'With separate research and health-data consent, the server receives a random participant number, relative study day, mood, energy, pressure and up to three selected support needs. It does not accept journal text, notes, names, email, student ID, device ID, precise location or exact client timestamps.'], ['Your controls', 'You can export local and pilot data, stop future research uploads, or delete the local content and linked pilot record from Privacy and data. Deletion and withdrawal require the participant-held key stored only on this device.'], ['Important anonymity boundary', 'Pilot records are pseudonymous while events remain linked by a random participant number. MindSHED does not keep a name-to-record mapping, but infrastructure and approved governance still need to be considered in the final privacy notice.']] },
  terms: { eyebrow: 'Wellbeing boundaries', title: 'Terms and wellbeing disclaimer', intro: 'MindSHED supports reflection and small wellbeing actions. It is not a clinical, diagnostic, monitoring or emergency service.', sections: [['When to seek help', 'Call 999 for immediate danger or risk to life. Use the Support screen for Samaritans, Shout and NHS 111 options in England.'], ['Using the activities', 'Check-ins, breathing, grounding and suggested activities are general wellbeing tools. They can be skipped or stopped at any time and are not medical advice.'], ['No monitoring', 'No person or automated system watches your journal, support plan or check-ins for emergencies. Choosing a low mood only presents support options on this device.'], ['Availability', 'Local features can work without the pilot service. Research uploads may pause for maintenance and will remain encrypted on this device until an eligible retry.']] },
  pilot: { eyebrow: 'University pilot', title: 'Research participation', intro: 'Research participation is optional and separate from ordinary university wellbeing support.', sections: [['What is proposed', 'The licensed seven-item SWEMWBS wellbeing pulse is available locally. Its research upload remains switched off until the digital presentation, participant feedback, data dictionary, safeguarding response and analysis plan receive the required approvals.'], ['What is excluded', 'Journal text, check-in notes, support-plan content and interactions with crisis resources are never research events.'], ['Changing your mind', 'Turning research off stops upload eligibility. Formal withdrawal records the withdrawal on the server and clears queued events. Treatment of previously collected data must follow the signed participant information and study protocol.']] },
  contact: { eyebrow: 'Real people', title: 'Contact MindSHED', intro: 'The production build will list distinct, verified routes for technical support, privacy rights and research questions.', sections: [['App support', 'A verified support email and accessibility-feedback route are still required.'], ['Privacy contact', 'The final controller name, address, privacy email and ICO registration must be inserted and approved.'], ['Research team', 'The University of Plymouth research contact and withdrawal route must be inserted from the final participant information sheet.']] },
} as const;

export default function LegalScreen() {
  const insets = useSafeAreaInsets();
  const { section = 'privacy' } = useLocalSearchParams<{ section?: keyof typeof COPY }>();
  const page = COPY[section] ?? COPY.privacy;
  return <ScrollView style={{ flex: 1, backgroundColor: MS.color.cream }} contentContainerStyle={{ paddingTop: insets.top + 12, paddingHorizontal: 18, paddingBottom: 40 }}><ScreenHeader eyebrow={page.eyebrow} title={page.title} description={page.intro} />{!LEGAL_DOCUMENTS_APPROVED && <View accessibilityRole="alert" style={{ marginTop: 18, borderRadius: 18, backgroundColor: '#F8E8D7', padding: 14 }}><BodyBold size={10.5} color={MS.color.inkSoft}>NOT APPROVED FOR PRODUCTION CONSENT</BodyBold><Body size={10.5} color={MS.color.muted} style={{ marginTop: 4 }}>The supplied legal drafts still contain unresolved placeholders and describe data flows not present in this pilot. Production enrollment remains disabled until a final matching version is signed off.</Body></View>}<View style={{ marginTop: 18, gap: 11 }}>{page.sections.map(([title, copy]) => <View key={title} style={{ borderRadius: MS.radius.xl, backgroundColor: MS.color.surface, padding: 17 }}><Heading size={15.5} color={MS.color.inkSoft}>{title}</Heading><Body size={11.5} color={MS.color.muted} style={{ marginTop: 5 }}>{copy}</Body></View>)}</View><BodyBold size={10} color={MS.color.faint} style={{ textAlign: 'center', marginTop: 22 }}>{LEGAL_DOCUMENTS_APPROVED ? 'APPROVED PILOT NOTICE' : 'ENGINEERING NOTICE · LEGAL APPROVAL REQUIRED'}</BodyBold></ScrollView>;
}
